version: '{build}'

platform: x64

configuration: Release

environment:
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  VCPKG_DEFAULT_TRIPLET: x64-windows

os: Visual Studio 2017

cache: c:\tools\vcpkg\installed\

before_build:
  - cd C:\tools\vcpkg
  - vcpkg install zlib:x64-windows
  - vcpkg install blosc:x64-windows
  - vcpkg install openexr:x64-windows
  - vcpkg install tbb:x64-windows
  - vcpkg install boost-iostreams:x64-windows
  - vcpkg install boost-system:x64-windows
  - vcpkg install boost-any:x64-windows
  - vcpkg install boost-algorithm:x64-windows
  - vcpkg install boost-uuid:x64-windows
  - vcpkg install boost-interprocess:x64-windows
  - vcpkg install boost-python:x64-windows
  - vcpkg integrate install

  # - adjust the PATH so that the vdb_test executable picks up all of the dll's correctly
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\build\openvdb\%CONFIGURATION%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake \
    -G"Visual Studio 15 2017 Win64" \
    -DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% \
    -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\cmake_install \
    -DCMAKE_TOOLCHAIN_FILE=C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake \
    -DOPENVDB_ABI_VERSION_NUMBER=6 \
    -DOPENVDB_BUILD_BINARIES=ON \
    -DOPENVDB_BUILD_VDB_PRINT=ON \
    -DOPENVDB_BUILD_VDB_LOD=ON \
    -DOPENVDB_BUILD_VDB_RENDER=ON \
    -DOPENVDB_BUILD_VDB_VIEW=OFF \
    -DOPENVDB_BUILD_PYTHON_MODULE=ON \
    -DOPENVDB_BUILD_UNITTESTS=ON \
    -DUSE_BLOSC=ON \
    ..
  - cmake --build . --parallel 4 --config %CONFIGURATION% --target install

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - build\openvdb\unittest\Release\vdb_test.exe -v
