
name: ax

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # run this workflow every midnight Tuesday
    - cron:  '0 0 * * 2'

jobs:
  linux-core:
    runs-on: ubuntu-16.04
    name: linux-vfx:${{ matrix.image }}-compiler:${{ matrix.compiler }}-llvm:${{ matrix.llvm }}-${{ matrix.build }}
    container:
      image: aswf/ci-vfxall:${{ matrix.image }}
    env:
      CXX: ${{ matrix.compiler }}
      LLVM_DIR: /github/home/llvm-${{ matrix.llvm }}-${{ matrix.compiler }}
    strategy:
      matrix:
        image: ['2019', '2020']
        compiler: ['g++', 'clang++']
        build: ['Release']
        llvm: ['6.0.0','7.0.0','8.0.0','9.0.0','10.0.0']
        # Debug builds
        include:
          - image: '2020'
            compiler: 'g++'
            build: 'Debug'
            llvm: '8.0.0'
          - image: '2020'
            compiler: 'clang++'
            build: 'Debug'
            llvm: '8.0.0'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      # Setup
      - name: llvm_cache
        id: llvm_cache
        uses: actions/cache@v2
        with:
          key: ${{ env.LLVM_DIR }}
          path: ${{ env.LLVM_DIR }}
      - name: install_llvm
        if: steps.llvm_cache.outputs.cache-hit != 'true'
        run: ./ci/install_llvm.sh ${{ matrix.llvm }} ${{ env.LLVM_DIR }}
