
name: Docs

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'pr/**'
    paths-ignore:
      - 'CHANGES'
      - 'openvdb_maya/**'
      - 'pendingchanges/**'
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'CHANGES'
      - 'openvdb_maya/**'
      - 'pendingchanges/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy docs?'
        required: true
        default: 'true'

jobs:
  doxygen:
    runs-on: ubuntu-latest
    env:
      CXX: g++
    container:
      image: aswf/ci-openvdb:2019
    steps:
    - uses: actions/checkout@v2
    - name: make_data
      run: |
        mkdir -p /usr/local/share/doc/OpenVDB/html
        touch /usr/local/share/doc/OpenVDB/html/test
    - name: pre_deploy
      # Overwrite global SSH configuration
      run: >
        echo "Host *
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
        " > /etc/ssh/ssh_config
    - name: deploy
      # only deploy documentation to gh-pages on a manual workflow dispatch
      if: |
        github.repository_owner == 'AcademySoftwareFoundation' &&
        github.event_name == 'workflow_dispatch' &&
        github.event.inputs.deploy == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: /usr/local/share/doc/OpenVDB/html
        destination_dir: documentation/doxygen
        external_repository: AcademySoftwareFoundation/openvdb-website
        publish_branch: doxygen
        commit_message: "doxygen documentation update"
