
name: Houdini Cache

on:
  schedule:
    # run this workflow every sunday at noon UTC
    - cron:  '0 12 * * 0'

# download the latest production version of Houdini, strip out headers,
# libraries and binaries required for building OpenVDB and if the build
# succeeds, put it into the GitHub Actions cache

jobs:
  houdini18_5:
    if: github.repository_owner == 'AcademySoftwareFoundation'
    runs-on: ubuntu-latest
    env:
      CXX: clang++
    container:
      image: aswf/ci-base:2020
    steps:
    - uses: actions/checkout@v2
    - name: download_houdini
      run: ./ci/download_houdini.sh 18.5 ON ON ${{ secrets.HOUDINI_CLIENT_ID }} ${{ secrets.HOUDINI_SECRET_KEY }}
    - name: install_houdini
      run: mv hou/hou.tar.gz . && tar -xzf hou.tar.gz
    - name: install_gtest
      run: ./ci/install_gtest.sh 1.10.0
    - name: build
      run: |
        cd hou && source houdini_setup_bash && cd -
        ./ci/build.sh -v --build-type=Release --components="core,hou,bin,python,test,axcore,axbin,axtest"
    - name: test
      run: ./ci/test.sh
    - name: write_houdini_cache
      uses: actions/cache@v2
      with:
        path: hou
        key: vdb1-houdini18_5-${{ hashFiles('hou/hou.tar.gz') }}

  houdini18_0:
    if: github.repository_owner == 'AcademySoftwareFoundation'
    runs-on: ubuntu-latest
    env:
      CXX: clang++
    container:
      image: aswf/ci-base:2019
    steps:
    - uses: actions/checkout@v2
    - name: download_houdini
      run: ./ci/download_houdini.sh 18.0 ON ON ${{ secrets.HOUDINI_CLIENT_ID }} ${{ secrets.HOUDINI_SECRET_KEY }}
    - name: install_houdini
      run: mv hou/hou.tar.gz . && tar -xzf hou.tar.gz
    - name: install_gtest
      run: ./ci/install_gtest.sh 1.10.0
    - name: build
      run: |
        cd hou && source houdini_setup_bash && cd -
        ./ci/build.sh -v --build-type=Release --components="core,hou,bin,python,test,axcore,axbin,axtest"
    - name: test
      run: ./ci/test.sh
    - name: write_houdini_cache
      uses: actions/cache@v2
      with:
        path: hou
        key: vdb1-houdini18_0-${{ hashFiles('hou/hou.tar.gz') }}
